// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: example/user.proto

package primitive

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
	primitive "primitive"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for User service

func NewUserEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for User service

type UserService interface {
	Create(ctx context.Context, in *CreateUserRequest, opts ...client.CallOption) (*primitive.Empty, error)
	Delete(ctx context.Context, in *primitive.Int64, opts ...client.CallOption) (*primitive.Empty, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) Create(ctx context.Context, in *CreateUserRequest, opts ...client.CallOption) (*primitive.Empty, error) {
	req := c.c.NewRequest(c.name, "User.Create", in)
	out := new(primitive.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Delete(ctx context.Context, in *primitive.Int64, opts ...client.CallOption) (*primitive.Empty, error) {
	req := c.c.NewRequest(c.name, "User.Delete", in)
	out := new(primitive.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	Create(context.Context, *CreateUserRequest, *primitive.Empty) error
	Delete(context.Context, *primitive.Int64, *primitive.Empty) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		Create(ctx context.Context, in *CreateUserRequest, out *primitive.Empty) error
		Delete(ctx context.Context, in *primitive.Int64, out *primitive.Empty) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) Create(ctx context.Context, in *CreateUserRequest, out *primitive.Empty) error {
	return h.UserHandler.Create(ctx, in, out)
}

func (h *userHandler) Delete(ctx context.Context, in *primitive.Int64, out *primitive.Empty) error {
	return h.UserHandler.Delete(ctx, in, out)
}
