// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/user.proto

package primitive

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	_ "proto/primitive"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_20657522f6c0c0ee, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "primitive.CreateUserRequest")
}

func init() { proto.RegisterFile("proto/example/user.proto", fileDescriptor_20657522f6c0c0ee) }

var fileDescriptor_20657522f6c0c0ee = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0xd5, 0x2f, 0x2d, 0x4e, 0x2d, 0xd2, 0x03,
	0x0b, 0x09, 0x71, 0x16, 0x14, 0x65, 0xe6, 0x66, 0x96, 0x64, 0x96, 0xa5, 0x4a, 0xc9, 0x43, 0x14,
	0xc1, 0x05, 0x10, 0x2c, 0x88, 0x5a, 0x25, 0x6f, 0x2e, 0x41, 0xe7, 0xa2, 0xd4, 0xc4, 0x92, 0xd4,
	0xd0, 0xe2, 0xd4, 0xa2, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x29, 0x2e, 0x0e, 0x90,
	0x71, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x70, 0x3e, 0x48, 0xae,
	0x20, 0xb1, 0xb8, 0xb8, 0x3c, 0xbf, 0x28, 0x45, 0x82, 0x09, 0x22, 0x07, 0xe3, 0x1b, 0xe5, 0x71,
	0xb1, 0x80, 0x8c, 0x11, 0xb2, 0xe0, 0x62, 0x83, 0x18, 0x2a, 0x24, 0xa3, 0x87, 0xb0, 0x10, 0xc3,
	0x1e, 0x29, 0x01, 0x24, 0x59, 0xd7, 0xdc, 0x82, 0x92, 0x4a, 0x21, 0x1d, 0x2e, 0x36, 0x97, 0xd4,
	0x9c, 0xd4, 0x92, 0x54, 0x21, 0x64, 0x39, 0xcf, 0xbc, 0x12, 0x33, 0x13, 0x4c, 0xd5, 0x49, 0x6c,
	0x60, 0x3f, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x62, 0x8a, 0xcc, 0x89, 0x0b, 0x01, 0x00,
	0x00,
}
